### ISSUE TITLE
Plugin macro not working in some pages

### ISSUE THREAD

**Issue by kmartens27** [Vandit1604/jenkins-docs#81]
While reviewing the versioned docs site, I found a handful of instances where the plugin macro is not working as expected. In some cases, it is the entire page, where others it is only one or two on the page (while others are working).

Themes for User Interface (https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/managing/ui-themes.html)
- All plugin macros on this page are broken

Monitoring Jenkins (https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/system-administration/monitoring.html)
- All plugin macros on this page are broken
- Jira macro not working either (note at top of page)

The macro appears to be working elsewhere throughout the site, so maybe there is something specific with these pages that is causing an issue. Would it be possible to investigate and find out what might be causing this?

**Comment by Vandit1604** [comment]
Hey Kevin I have raised this PR. Do review it in your own time.
https://github.com/Vandit1604/jenkins-docs/pull/88
